name: vendor_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^7.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  logger: ^2.6.2
  shared_preferences: ^2.5.4
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "images/logo/vendoor-logo.png"
  android : "launcher_icon"
  ios: true

flutter:
  uses-material-design: true
  assets:
   - images/
   - images/logo/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Italic-VariableFont_wght.ttf
        - asset: fonts/Raleway-VariableFont_wght.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
    - family: Roboto 
      fonts:
        - asset: fonts/Roboto-Italic-VariableFont_wdth,wght.ttf 
        - asset: fonts/Roboto-VariableFont_wdth,wght.ttf 
        - asset: fonts/RobotoMono-Italic-VariableFont_wght.ttf 
        - asset: fonts/RobotoMono-VariableFont_wght.ttf